Added support for output to Mqtt broker
InfernoEmbedded/PowerScraper pull request #15
Opened 2021-03-03 19:45 UTC by saemmy

2021-03-29 23:49 UTC, deece requested changes

2021-03-29 23:49 UTC, deece commented on Outputs/Mqtt.py
> +        client.connect(self.mqtt_host, self.mqtt_port, self.mqtt_keepalive)
Hmm, I think we would be better off connecting on class instantiation and keeping the connection open, rather than connecting & disconnecting each time we have a new set of outputs.

We will need to handle the case where the client is disconnected and attempt a reconnect, and also if we get another send request while the client is already attempting to connect.

2022-06-27 21:41 UTC, sumnerboy12 commented
Is this still likely to be merged at some point? This would be a great addition IMO.

2025-04-12 03:46 UTC, deece commented
Obsoleted by 3bf3a5e994810543a94924777bb3ed61cee90451

2025-04-12 03:46 UTC, closed without merging